# Generated by Django 5.2.4 on 2025-07-21 11:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Blog/images')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('author_name', models.CharField(max_length=250)),
                ('author_image', models.ImageField(upload_to='Blog/images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
