# Generated by Django 5.2.4 on 2025-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('cover_image', models.ImageField(upload_to='Audio/images')),
                ('audio_file', models.FileField(upload_to='Audio/files')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
