# Generated by Django 5.2.4 on 2025-07-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subcategory'),
        ),
    ]
