# Generated by Django 5.2.4 on 2025-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_audio_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='creeds/images/')),
                ('pdf_file', models.FileField(upload_to='creeds/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
