# Generated by Django 5.2.4 on 2025-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_creedconfession_delete_creed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='creeds_confessions/images/')),
                ('pdf', models.FileField(upload_to='creeds_confessions/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreedConfession',
        ),
    ]
