# Generated by Django 5.2.4 on 2025-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_creed_delete_creedconfession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='books/images/')),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
