# Generated by Django 5.2.4 on 2025-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReformedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotes_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
